version: '3'
services:
  neo4j:
      image: neo4j:3.5.26
      container_name: neo4j_amundsen
      environment:
        - NEO4J_AUTH=neo4j/test
      ulimits:
        nofile:
          soft: 40000
          hard: 40000
      ports:
          - 7474:7474
          - 7687:7687
      volumes:
          - ./example/docker/neo4j/conf:/var/lib/neo4j/conf
          - neo4j_data:/data
      networks:
        - amundsennet
  elasticsearch:
      image: elasticsearch:7.13.3
      container_name: es_amundsen
      ports:
          - 9200:9200
      networks:
        - amundsennet
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      environment:
        - discovery.type=single-node
      volumes:
        - es_data:/usr/share/elasticsearch/data
  amundsensearch:
      build:
        context: .
        dockerfile: Dockerfile.search.public
      container_name: amundsensearch
      ports:
        - 5001:5001
      depends_on:
        - elasticsearch
      networks:
        - amundsennet
      environment:
        - PROXY_ENDPOINT=es_amundsen
        - FLASK_APP_MODULE_NAME=flaskoidc
        - FLASK_APP_CLASS_NAME=FlaskOIDC
        - FLASK_OIDC_CONFIG_URL=http://keycloak:8080/auth/realms/master/.well-known/openid-configuration
        - SESSION_TYPE=sqlalchemy
        - FLASK_OIDC_SECRET_KEY=base-flask-oidc-secret-key
  amundsenmetadata:
      build:
        context: .
        dockerfile: Dockerfile.metadata.public
      container_name: amundsenmetadata
      depends_on:
        - neo4j
      ports:
        - 5002:5002
      networks:
        - amundsennet
      environment:
        - PROXY_HOST=bolt://neo4j_amundsen
        - FLASK_APP_MODULE_NAME=flaskoidc
        - FLASK_APP_CLASS_NAME=FlaskOIDC
        - FLASK_OIDC_CONFIG_URL=http://keycloak:8080/auth/realms/master/.well-known/openid-configuration
        - SESSION_TYPE=sqlalchemy
        - FLASK_OIDC_SECRET_KEY=base-flask-oidc-secret-key
  amundsenfrontend:
      build:
        args:
          SEARCHSERVICE_BASE: http://amundsensearch:5001
          METADATASERVICE_BASE: http://amundsenmetadata:5002
        context: .
        dockerfile: Dockerfile.frontend.local
      container_name: amundsenfrontend
      depends_on:
        - amundsenmetadata
        - amundsensearch
      ports:
        - 5000:5000
      networks:
        - amundsennet
      environment:
        - SEARCHSERVICE_BASE=http://amundsensearch:5001
        - METADATASERVICE_BASE=http://amundsenmetadata:5002
        - FLASK_APP_MODULE_NAME=flaskoidc
        - FLASK_APP_CLASS_NAME=FlaskOIDC
        - FLASK_OIDC_PROVIDER_NAME=keycloak
        - FLASK_OIDC_SCOPES=openid email profile
        - FLASK_OIDC_CLIENT_ID=amundsen-frontend
        - FLASK_OIDC_CLIENT_SECRET=9f0df761-8107-4c64-8083-6d5ce9dd3aee
        - FLASK_OIDC_REDIRECT_URI=/auth
        - FLASK_OIDC_CONFIG_URL=http://keycloak:8080/auth/realms/master/.well-known/openid-configuration
        - SESSION_TYPE=sqlalchemy
        - FLASK_OIDC_SECRET_KEY=base-flask-oidc-secret-key
      depends_on:
        - keycloak

  keycloak:
      image: jboss/keycloak:15.0.2
      container_name: keycloak
      ports:
        - 8080:8080
        - 8443:8443
      networks:
        - amundsennet
      environment:
        - DB_VENDOR=h2
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=secret
      volumes:
        - keycloak:/opt/jboss/keycloak/standalone/data

networks:
  amundsennet:

volumes:
  keycloak:
  es_data:
  neo4j_data:
